name: keya_night
on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time (JST)
        run: echo "START_TIME=$(TZ='Asia/Tokyo' date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - id: playwright-cache
        name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies and Playwright
        run: |
          npm ci
          if [ "${{ steps.playwright-cache.outputs.cache-hit }}" != "true" ]; then
            npx playwright install --with-deps
          fi

      - name: Run Playwright tests
        run: npx playwright test night.spec

      - name: Set End Time (JST) and Output Times
        run: |
          END_TIME=$(TZ='Asia/Tokyo' date '+%Y-%m-%d %H:%M:%S')
          echo "START_TIME: $START_TIME"
          echo "END_TIME: $END_TIME"
        env:
          START_TIME: ${{ env.START_TIME }}
